services:
  frontend:
    build: .
    container_name: nestfront_container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
      - PORT = 3000
    command: ["npm", "run", "dev"]
